services:
  - type: web
    name: flask-madlibs
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
